# Generated by Django 5.2.5 on 2025-08-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
